# Generated by Django 5.1.1 on 2024-09-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointactivity',
            name='activity_data',
            field=models.JSONField(),
        ),
    ]
