# Generated by Django 5.1.1 on 2024-09-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_device_incidentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
    ]
