# Generated by Django 5.1.1 on 2024-09-28 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_device_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpointactivity',
            name='activity_data',
            field=models.TextField(),
        ),
    ]
