# Generated by Django 5.1.1 on 2024-09-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_alter_endpointactivity_activity_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentlog',
            old_name='log_data',
            new_name='description',
        ),
    ]
