# Generated by Django 5.1.1 on 2024-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_rename_log_data_incidentlog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='isolation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
