# Generated by Django 5.1.1 on 2025-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_device_isolation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='last_bruteforce_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
