# Generated by Django 5.1.1 on 2025-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='auth_token',
            field=models.CharField(default='default_token', max_length=100),
        ),
    ]
