# Generated by Django 5.1.1 on 2025-10-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0010_device_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='auth_token',
            field=models.CharField(default='my_secret_token_123', max_length=100),
        ),
    ]
