# Generated by Django 5.1.1 on 2025-10-10 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_alter_device_auth_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ddos_connection_threshold',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='device',
            name='ddos_traffic_threshold_mb',
            field=models.FloatField(default=50.0),
        ),
    ]
