# Generated by Django 5.1.1 on 2025-10-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0012_device_ddos_connection_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='enable_behavioral_analysis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='device',
            name='enable_ransomware_trap',
            field=models.BooleanField(default=True),
        ),
    ]
