# Generated by Django 5.1.1 on 2025-10-28 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0013_device_enable_behavioral_analysis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='last_bruteforce_check',
        ),
    ]
