# Generated by Django 5.1.1 on 2025-11-07 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0014_remove_device_last_bruteforce_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
